### ISSUE TITLE
Blank UI

### ISSUE THREAD

**Issue by mayankshukla5031** [lemieux/react-messenger-plugin#3]
react-messenger-plugin is working fine if the login is success, and shows the Messenger button properly, but if the login process fails, then it shows the blank div with no info, it that case it should show some error message "Kindly login with Facebook first" or some other. We tried to put some element after 10 sec but that was not working, Kindly provide some info.

**Comment by lemieux** [comment]
Hi, 

unfortunately there isn't much I can do about this as this library is simply wrapping the official Facebook lib. However, I think we experienced that behavior while working with the plugin when the Facebook page/app is in dev mode and the person logging in is not part of the dev team for that page.

See documentation here https://developers.facebook.com/docs/messenger-platform/plugin-reference/send-to-messenger

Also see the FAQ here https://developers.facebook.com/docs/messenger-platform/faq

> How come I can't see the "Send to Messenger" plugin?

> When an app is in development mode only admins, developers and testers of the app are able to view the plugin. After the app is reviewed and approved, you make the app available to the public in the App Review tab in the App Dashboard.

I'll close this issue since there isn't much I can do in this library.
